# Generated by Django 4.2.7 on 2026-04-06 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_marks_obtained', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('whatsapp_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('image', models.ImageField(upload_to='submissions/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed/')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='grader.copysubmission')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=20)),
                ('total_marks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('question_text', models.TextField()),
                ('q_type', models.CharField(choices=[('mcq', 'MCQ'), ('short', 'Short Answer'), ('long', 'Long Answer')], max_length=10)),
                ('correct_answer', models.TextField(help_text='MCQ: A/B/C/D | Short/Long: model answer')),
                ('options', models.TextField(blank=True, help_text='MCQ options comma-separated: A,B,C,D')),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated important keywords')),
                ('max_marks', models.FloatField(default=1)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='grader.questionpaper')),
            ],
            options={
                'ordering': ['question_no'],
            },
        ),
        migrations.AddField(
            model_name='copysubmission',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grader.questionpaper'),
        ),
        migrations.AddField(
            model_name='copysubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grader.student'),
        ),
        migrations.CreateModel(
            name='AnswerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(blank=True)),
                ('keywords_found', models.TextField(blank=True)),
                ('keywords_missing', models.TextField(blank=True)),
                ('keyword_score', models.FloatField(default=0)),
                ('ai_marks', models.FloatField(default=0)),
                ('final_marks', models.FloatField(default=0)),
                ('ai_feedback', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grader.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='grader.copysubmission')),
            ],
            options={
                'ordering': ['question__question_no'],
            },
        ),
    ]
